         
********************************************************************
Job Name:r_cl0,Job ID:681651,Allocate Nodes:172-16-30-[45-46]
********************************************************************


--- Logging error ---
Traceback (most recent call last):
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 298, in <module>
    train_cnn_model('pnasnet5large_class0', gpu_ids, batch_size)
  File "main.py", line 258, in train_cnn_model
    logging.debug("Let's use ", len(gpu_ids), " GPUs!")
Message: "Let's use "
Arguments: (16, ' GPUs!')
Traceback (most recent call last):
  File "main.py", line 298, in <module>
    train_cnn_model('pnasnet5large_class0', gpu_ids, batch_size)
  File "main.py", line 263, in train_cnn_model
    model = torch.nn.DataParallel(model, device_ids=gpu_ids, output_device=gpu_ids[0])
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/torch/cuda/__init__.py", line 302, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
